model:
  base_learning_rate: 1.5e-6
  target: ldm.models.autoencoder_new.AutoencoderKL
  params:
    monitor: "val/rec_loss"
    embed_dim: 4
    lossconfig:
      target: ldm.modules.losses.LPIPSWithDiscriminator
      params:
        disc_start: 50001
        kl_weight: 0.000001
        disc_weight: 0.5
        perceptual_weight: 1.0
        disc_in_channels: 5

    ddconfig:
      double_z: True
      z_channels: 4
      resolution: 128
      in_channels: 5
      out_ch: 5
      ch: 128
      ch_mult: [ 1,2,4 ]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: [ ]
      dropout: 0.0

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 8
    wrap: True
    train:
      target: ldm.data.5c.Train
      params:
        npy_path: /data2/wangxuesong/morphdata/data_1115/application/for_fig5_expand/inside_target/train_test/train_img_5c.npy
        gene_path: /data2/wangxuesong/morphdata/data_1115/application/for_fig5_expand/inside_target/train_test/train_gene.npy
        size: 128
    validation:
      target: ldm.data.5c.Val
      params:
        npy_path: /data2/wangxuesong/morphdata/data_1115/application/for_fig5_expand/inside_target/train_test/test_img_5c.npy
        gene_path: /data2/wangxuesong/morphdata/data_1115/application/for_fig5_expand/inside_target/train_test/test_gene.npy
        size: 128


lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 1000
        max_images: 8
        increase_log_steps: True

  trainer:
    benchmark: True
    accumulate_grad_batches: 2
