model:
  base_learning_rate: 6.0e-6   # set to target_lr by starting main.py with '--scale_lr False'
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0155
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    loss_type: l1
    first_stage_key: "image"
    cond_stage_key: gene_vector
    image_size: 32
    channels: 4
    cond_stage_trainable: False
    conditioning_key: crossattn
    scale_by_std: True
    monitor: 'val/loss_simple_ema'

    scheduler_config: 
      target: ldm.lr_scheduler.LambdaLinearScheduler
      params:
        warm_up_steps: [200]
        cycle_lengths: [10000000000000]
        f_start: [1.e-6]
        f_max: [1.]
        f_min: [ 1.]

    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 32
        in_channels: 4
        out_channels: 4
        model_channels: 192
        attention_resolutions: [ 1, 2, 4, 8 ]   # 32, 16, 8, 4
        num_res_blocks: 2
        channel_mult: [ 1,2,2,4,4 ]  # 32, 16, 8, 4, 2
        num_heads: 8
        use_scale_shift_norm: True
        resblock_updown: True
        use_spatial_transformer: True
        transformer_depth: 1
        context_dim: 12

    first_stage_config:
      target: ldm.models.autoencoder_new.AutoencoderKL
      params:
        embed_dim: 4
        monitor: "val/rec_loss"
        ckpt_path: "MorphDiff/checkpoints/drug_mvae.ckpt"
        ddconfig:
          double_z: True
          z_channels: 4
          resolution: 128
          in_channels: 5
          out_ch: 5
          ch: 128
          ch_mult: [ 1,2,4 ]  # num_down = len(ch_mult)-1
          num_res_blocks: 2
          attn_resolutions: [ ]
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity
    cond_stage_config: 
      target: ldm.modules.encoders.modules_new.GeneEmbedder
      params:
        gene_dim: 977
        output_dim: 32
        key: gene_vector

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 8
    num_workers: 5
    wrap: False
    train:
      target: ldm.data.5c.Train
      params:
        npy_path: /data2/wangxuesong/morphdata/data_1115/application/for_fig5_expand/inside_target/train_test/train_img_5c.npy
        gene_path: /data2/wangxuesong/morphdata/data_1115/application/for_fig5_expand/inside_target/train_test/train_gene.npy
        size: 128
    validation:
      target: ldm.data.5c.Val
      params:
        npy_path: /data2/wangxuesong/morphdata/data_1115/application/for_fig5_expand/inside_target/train_test/test_img_5c.npy
        gene_path: /data2/wangxuesong/morphdata/data_1115/application/for_fig5_expand/inside_target/train_test/test_gene.npy
        size: 128

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 1500
        max_images: 8
        increase_log_steps: False
        log_first_step: False
    metrics_over_trainsteps_checkpoint:
      target: pytorch_lightning.callbacks.ModelCheckpoint
      params:
        every_n_train_steps: 1500


  trainer:
    benchmark: True